services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_CONTACT_ENDPOINT: ${REACT_APP_CONTACT_ENDPOINT:-https://api.batterystringstudio.com/contact}
        REACT_APP_STUDIO_API: ${REACT_APP_STUDIO_API:-https://api.batterystringstudio.com}
        REACT_APP_WEBSITE_DOMAIN: ${REACT_APP_WEBSITE_DOMAIN:-https://staging.batterystringstudio.com}
        REACT_APP_LAB_URL: ${REACT_APP_LAB_URL:-https://lab-staging.batterystringstudio.com}
        REACT_APP_SCALES_URL: ${REACT_APP_SCALES_URL:-https://scales-staging.batterystringstudio.com}
        REACT_APP_STUDIO_EMAIL: ${REACT_APP_STUDIO_EMAIL:-hello@batterystringstudio.com}
    container_name: bss_studio_staging
    ports:
      - "8088:80"
    restart: unless-stopped
