name = "brevo-contact-worker"
main = "src/index.js"
compatibility_date = "2024-11-07"

account_id = "6994f7f6c31b227cc8a0b96af83eb060"

route = { pattern = "api.jarredcianciulli.com/contact", zone_name = "jarredcianciulli.com" }

[vars]
FROM_EMAIL = "jarred@batterystringstudio.com"
TO_EMAIL = "jarred@batterystringstudio.com"
WEBSITE_DOMAIN = "https://batterystringstudio.com"

[env.dev.vars]
WEBSITE_DOMAIN = "http://localhost:3000"

